import type { DiscoveryReport } from "./types";

export const sampleReport: DiscoveryReport = {
  generatedAt: "2026-06-03T01:00:00.000Z",
  date: "2026-06-03",
  source: "sample-fallback",
  queryWindow: {
    createdAfter: "2026-05-13",
    pushedAfter: "2026-05-27",
  },
  items: [
    {
      id: "modelcontextprotocol-servers",
      kind: "Skill",
      category: "MCP",
      name: "MCP Servers",
      fullName: "modelcontextprotocol/servers",
      repoUrl: "https://github.com/modelcontextprotocol/servers",
      description: "A collection of reference Model Context Protocol servers.",
      summaryZh:
        "这是一个 MCP 服务器集合，适合给 AI 助手接入文件、数据库、浏览器或开发工具等外部能力。",
      whyUseful: [
        "能把外部工具能力标准化接入 agent 工作流。",
        "适合作为自建 MCP server 的参考实现。",
      ],
      useCases: ["给桌面 AI 助手接入常用工具", "学习 MCP server 的结构", "挑选可复用的 agent 工具能力"],
      quickStart: ["官方 README 会按具体 server 给出启动命令，请优先选择需要的 server 再配置。"],
      installSteps: ["官方未提供统一安装步骤，请进入对应 server 目录查看 README。"],
      skillIntegration:
        "按目标 MCP server 的 README，把启动命令写入支持 MCP 的客户端配置中。",
      caveats: ["不同 server 的运行环境不同，使用前需要分别检查依赖和权限。"],
      language: "TypeScript",
      topics: ["mcp", "agent", "tools"],
      tags: ["MCP", "AI Skill"],
      stars: 0,
      forks: 0,
      openIssues: 0,
      starDelta24h: 0,
      growthNote: "estimated",
      score: 90,
      license: "unknown",
      owner: {
        login: "modelcontextprotocol",
        avatarUrl: "https://github.com/modelcontextprotocol.png",
        url: "https://github.com/modelcontextprotocol",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2026-06-03T00:00:00Z",
      pushedAt: "2026-06-03T00:00:00Z",
    },
    {
      id: "vercel-ai",
      kind: "Project",
      category: "Library",
      name: "AI SDK",
      fullName: "vercel/ai",
      repoUrl: "https://github.com/vercel/ai",
      description: "Build AI-powered applications with React, Next.js, Vue, Svelte, and Node.",
      summaryZh:
        "这是一个 AI 应用开发 SDK，适合构建聊天、生成、工具调用和流式输出类产品。",
      whyUseful: ["封装了多模型调用和前端流式交互。", "适合快速搭建 AI 产品原型。"],
      useCases: ["AI 聊天界面", "结构化生成", "工具调用和 agent UI"],
      quickStart: ["npm install ai"],
      installSteps: ["npm install ai"],
      caveats: ["具体 provider 仍需配置对应 API Key。"],
      language: "TypeScript",
      topics: ["ai", "sdk", "react"],
      tags: ["Library", "AI"],
      stars: 0,
      forks: 0,
      openIssues: 0,
      starDelta24h: 0,
      growthNote: "estimated",
      score: 86,
      license: "unknown",
      owner: {
        login: "vercel",
        avatarUrl: "https://github.com/vercel.png",
        url: "https://github.com/vercel",
      },
      createdAt: "2023-01-01T00:00:00Z",
      updatedAt: "2026-06-03T00:00:00Z",
      pushedAt: "2026-06-03T00:00:00Z",
    },
  ],
};
